config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get 'auth/:provider/callback',  to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/dashboard', as: 'dashboard', to: 'dashboard#index'
  get '/profile', as: 'profile', to: 'users#show'
  get '/gifts', as: 'gifts', to: 'gifts#index'
  get '/favorites', as: 'favorites', to: 'favorites#index'

  resources :charges, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :user
  belongs_to :image

  def self.total_amount(image_id)
    dollar_amount(where(image_id: image_id).sum(:amount))
  end

  private

    def self.dollar_amount(amount)
      ActionController::Base.helpers.number_to_currency(amount/100)
    end
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :gifts

  validates_uniqueness_of :nps_id
end

app/models/image_list.rb
class ImageList
  attr_reader :images, :total

  def initialize(info)
    @total = info[:total]
    @images = create_images(info[:data])
  end

  def create_images(info)
    images = info.map do |park|
      park[:images].map do |image|
        unless Image.find_by(nps_id: image[:id])
          url = begin
                  Cloudinary::Uploader.upload(image[:url], transformation: [{width: 1000, crop: :fit}])["secure_url"]
                rescue CloudinaryException
                  next
                end

          Image.create(park: park[:name],
                       park_url: park[:url],
                       credit: image[:credit],
                       alt_text: image[:altText],
                       title: image[:title],
                       caption: image[:caption],
                       url: url,
                       nps_id: image[:id])
       end
      end
    end.flatten
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gifts

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @description = params[:park]
    @image_url = params[:url]
  end

  def create
    CreateChargeJob.perform_later(500, params[:stripeEmail], params[:stripeToken], params[:description])
    image = Image.find_by(url: params[:url])
    current_user.gifts.create(image: image, amount: 500)
    redirect_to dashboard_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @images = ImagePresenter.images(params[:park])
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  def index
    @gifts = GiftPresenter.new(current_user, params[:park])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to dashboard_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<section class="clear-fix">
  <div class="col-4 mx-auto center bg-soft-white rounded">
    <%= form_tag charges_path(description: @description, url: @image_url) do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        <label class="amount">
          <span><h2>Donate: $5.00</h2></span>
        </label>
      </article>
      <div class="pb2">
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description = "<%= @description %>"
                data-amount="500"
                data-locale="auto">
        </script>
      </div>
    <% end %>
  </div>
</section>

app/views/dashboard/index.html.erb
<%= render partial: './navbar' %>
<section class="spacer">

</section>

<div class="col-6 mx-auto">
  <div class="center mb1">

    <%= form_tag dashboard_path, method: :get do %>
      <%= text_field_tag "park", nil, placeholder: "Search Images by Park Name", class: "mb1 search-text"%>
    <% end %>
    <%= link_to "Random Images", dashboard_path, class: "col-9 search-text text-decoration-none black" %>
  </div>
</div>

<section class="m0 images col-6 mx-auto">
  <% @images.each do |image| %>
    <div class="mb1 p1 rounded image bg-soft-white">
      <h2 class="m0 center block"><%=link_to image.park, image.park_url, target: :_blank, class: "text-decoration-none black" %></h2>
      <div class="gift-wrapper">
        <%= image_tag "#{image.url}", class: "mx-auto block med-image rounded" %>
        <div class="centered">
          <h2><%= link_to fa_icon("dollar", class: "big-icon center"), new_charge_path(park: "#{image.park}", url: "#{image.url}"), class: "text-decoration-none black", id: "give" %></h2>
        </div>
      </div>
      <p class="m1 center block"><%= image.caption %></p>
    </div>
  <% end %>
</section>

app/views/favorites/index.html.erb
<%= render partial: './navbar' %>

app/views/gifts/index.html.erb
<%= render partial: './navbar' %>

<section class="spacer">

</section>

<h2 class="center">Total Donations: <%= @gifts.total_donations %></h2>

<div class="col-6 mx-auto">
  <div class="center mb1">

    <%= form_tag gifts_path, method: :get do %>
      <%= text_field_tag "park", nil, placeholder: "Search Gifts by Park Name", class: "mb1 search-text"%>
    <% end %>
    <%= link_to "All Gifts", '/gifts', class: "col-9 search-text text-decoration-none black" %>
  </div>
</div>

<section class="m0 gifts col-6 mx-auto">
  <% @gifts.gift_array.each do |gift| %>
    <div class="mb1 p1 rounded image bg-soft-white">
      <h2 class="m0 center block"><%=link_to gift.image.park, gift.image.park_url, target: :_blank, class: "text-decoration-none black" %></h2>
      <div class="gift-wrapper">
        <%= image_tag "#{gift.image.url}", class: "mx-auto block med-image rounded" %>
        <div class="centered">
          <h1><%= @gifts.all.total_amount(gift.image_id) %></h1>
          <h2><%= link_to fa_icon("dollar", class: "big-icon center"), new_charge_path(park: "#{gift.image.park}", url: "#{gift.image.url}"), class: "text-decoration-none black", id: "give" %></h2>
        </div>
      </div>
      <p class="m1 center block"><%= gift.image.caption %></p>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndChecks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans|Dosis:400,800" rel="stylesheet" type="text/css" />
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
  </head>

  <body class="m0">
    <%= yield %>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body class="background-image" style=<%= "background-image:url(#{@image_url});" %>>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<%= render partial: './navbar' %>
<section class="spacer">

</section>

<section class="ml2">
  <h2>Name: <%= current_user.name %></h2>
  <h2>Email: <%= current_user.email %></h2>
</section>

app/views/welcome/index.html.erb
<section class='cover-image m0 vh100 flex flex-column'>
  <p class="ml-auto m1 bg-soft-white rounded p1">Park Login</p>
  <div class="col-12 mx-auto m4 center bg-soft-white rounded">
    <h1 class="m2">Parks and Checks</h1>
    <p><%= link_to "Sign Up/Sign In", "/auth/google", class: "text-decoration-none black"%></p>
  </div>
</section>